apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: system
  labels:
    app: api-server
    app.kubernetes.io/name: api-server
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: system
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-server-manager
      containers:
      - name: api-server
        args:
          - /app/manager
          - -conf=/data/conf
          - -global-config-namespace=nautes
        image: harbor.bluzin.io/luojinxu/api-server:c5dc2d1d8c291f95349bca50aeb3ce76a41438df-60fe187f-f68f-43f0-bc61-0d819dfdee2c
        env:
        - name: RESOURCES_LAYOUT
          value: /usr/local/share/resources_layout.yaml
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  cp /opt/nautes/out/pki/ca.crt /usr/local/share/ca-certificates/
                  update-ca-certificates
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: api-server-secret
          mountPath: /opt/nautes/out/pki
        - name: resources-layout
          mountPath: /usr/local/share/
          readOnly: true
        - name: third-part-components
          mountPath: /opt/nautes/thirdPartComponents
          readOnly: true
        - name: nautes-tls-certs
          mountPath: /opt/nautes/ssl/
        - name: api-server-log
          readOnly: true
          mountPath: /log
        - name: ca-certs
          mountPath: /usr/local/share/ca-certificates/
      volumes:
      - name: resources-layout
        configMap:
          name: resources-layout
          items:
          - key: resources_layout.yaml
            path: resources_layout.yaml
      - name: third-part-components
        configMap:
          name: third-part-components
          items:
          - key: thirdPartComponents
            path: thirdPartComponents.yaml
      - name: nautes-tls-certs
        configMap:
          name: nautes-tls-certs
      - name: api-server-secret
        projected:
          sources:
          - secret:
              name: api-server-cert
      - name: api-server-log
        persistentVolumeClaim:
          claimName: api-server-log
      - name: ca-certs
        emptyDir: {}
